version: '3.9'

services:
  web:
    build: .
    command: bash -c "python manage.py migrate --noinput && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/code
    ports:
      - "8080:8080"
    env_file:
      - .env
  redis:
    container_name: redis
    image: redis:alpine
    restart: unless-stopped
  celery:
    build: .
    restart: always
    command: celery worker --app=notification_service --loglevel=info
    volumes:
      - .:/code
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      - redis
      - web
  dashboard:
    container_name: dashboard
    build: .
    command: flower --app=notification_service --port=5555 broker=redis://redis:6379/0
    ports:
      - 5555:5555
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      - redis
      - web
      - celery
  test:
    image: registry.gitlab.com/namedima4/mailling_test:${CI_BUILD_REF_NAME}
    command: python manage.py test
    restart: "no"
